// Flat word list for Miles' Spelling Game. Just data - no tier field.
// A word's tier is derived from its length by tierForWord() in app.js
// (3 letters = tier 1, 4 = 2, 5 = 3, 6-7 = 4, 8+ = 5), so adding a word
// is a one-liner and changing the tier rules is a single edit there.
// Order below does not matter; grouped by length only for readability.
// Images: Twemoji (CC-BY 4.0) - see ATTRIBUTIONS.md
const WORDS = [
  { word: "cat", image: "assets/images/cat.svg" },
  { word: "dog", image: "assets/images/dog.svg" },
  { word: "sun", image: "assets/images/sun.svg" },
  { word: "hat", image: "assets/images/hat.svg" },
  { word: "pig", image: "assets/images/pig.svg" },
  { word: "cup", image: "assets/images/cup.svg" },
  { word: "bed", image: "assets/images/bed.svg" },
  { word: "fox", image: "assets/images/fox.svg" },
  { word: "bus", image: "assets/images/bus.svg" },
  { word: "egg", image: "assets/images/egg.svg" },
  { word: "box", image: "assets/images/box.svg" },
  { word: "hen", image: "assets/images/hen.svg" },
  { word: "bag", image: "assets/images/bag.svg" },
  { word: "van", image: "assets/images/van.svg" },
  { word: "key", image: "assets/images/key.svg" },
  { word: "owl", image: "assets/images/owl.svg" },
  { word: "cow", image: "assets/images/cow.svg" },
  { word: "bee", image: "assets/images/bee.svg" },

  { word: "frog", image: "assets/images/frog.svg" },
  { word: "lion", image: "assets/images/lion.svg" },
  { word: "duck", image: "assets/images/duck.svg" },
  { word: "fish", image: "assets/images/fish.svg" },
  { word: "bird", image: "assets/images/bird.svg" },
  { word: "boat", image: "assets/images/boat.svg" },
  { word: "bear", image: "assets/images/bear.svg" },
  { word: "sofa", image: "assets/images/sofa.svg" },
  { word: "bath", image: "assets/images/bath.svg" },
  { word: "hand", image: "assets/images/hand.svg" },
  { word: "foot", image: "assets/images/foot.svg" },
  { word: "book", image: "assets/images/book.svg" },
  { word: "tree", image: "assets/images/tree.svg" },
  { word: "drum", image: "assets/images/drum.svg" },
  { word: "star", image: "assets/images/star.svg" },
  { word: "moon", image: "assets/images/moon.svg" },
  { word: "kite", image: "assets/images/kite.svg" },
  { word: "goat", image: "assets/images/goat.svg" },
  { word: "crab", image: "assets/images/crab.svg" },
  { word: "cake", image: "assets/images/cake.svg" },
  { word: "leaf", image: "assets/images/leaf.svg" },
  { word: "bell", image: "assets/images/bell.svg" },

  { word: "train", image: "assets/images/train.svg" },
  { word: "chair", image: "assets/images/chair.svg" },
  { word: "chips", image: "assets/images/chips.svg" },
  { word: "lemon", image: "assets/images/lemon.svg" },
  { word: "sheep", image: "assets/images/sheep.svg" },
  { word: "horse", image: "assets/images/horse.svg" },
  { word: "zebra", image: "assets/images/zebra.svg" },
  { word: "koala", image: "assets/images/koala.svg" },
  { word: "camel", image: "assets/images/camel.svg" },
  { word: "snake", image: "assets/images/snake.svg" },
  { word: "whale", image: "assets/images/whale.svg" },
  { word: "shark", image: "assets/images/shark.svg" },
  { word: "mouse", image: "assets/images/mouse.svg" },
  { word: "apple", image: "assets/images/apple.svg" },
  { word: "spoon", image: "assets/images/spoon.svg" },
  { word: "glass", image: "assets/images/glass.svg" },
  { word: "slide", image: "assets/images/slide.svg" },
  { word: "phone", image: "assets/images/phone.svg" },
  { word: "tiger", image: "assets/images/tiger.svg" },
  { word: "panda", image: "assets/images/panda.svg" },
  { word: "snail", image: "assets/images/snail.svg" },
  { word: "bread", image: "assets/images/bread.svg" },
  { word: "pizza", image: "assets/images/pizza.svg" },
  { word: "clock", image: "assets/images/clock.svg" },
  { word: "cloud", image: "assets/images/cloud.svg" },

  { word: "monkey", image: "assets/images/monkey.svg" },
  { word: "guitar", image: "assets/images/guitar.svg" },
  { word: "cheese", image: "assets/images/cheese.svg" },
  { word: "potato", image: "assets/images/potato.svg" },
  { word: "orange", image: "assets/images/orange.svg" },
  { word: "pepper", image: "assets/images/pepper.svg" },
  { word: "cereal", image: "assets/images/cereal.svg" },
  { word: "rabbit", image: "assets/images/rabbit.svg" },
  { word: "parrot", image: "assets/images/parrot.svg" },
  { word: "spider", image: "assets/images/spider.svg" },
  { word: "banana", image: "assets/images/banana.svg" },
  { word: "grapes", image: "assets/images/grapes.svg" },
  { word: "carrot", image: "assets/images/carrot.svg" },
  { word: "rocket", image: "assets/images/rocket.svg" },
  { word: "flower", image: "assets/images/flower.svg" },

  { word: "giraffe", image: "assets/images/giraffe.svg" },
  { word: "dolphin", image: "assets/images/dolphin.svg" },
  { word: "gorilla", image: "assets/images/gorilla.svg" },
  { word: "penguin", image: "assets/images/penguin.svg" },
  { word: "octopus", image: "assets/images/octopus.svg" },
  { word: "scooter", image: "assets/images/scooter.svg" },
  { word: "balloon", image: "assets/images/balloon.svg" },
  { word: "rainbow", image: "assets/images/rainbow.svg" },
  { word: "unicorn", image: "assets/images/unicorn.svg" },

  { word: "elephant", image: "assets/images/elephant.svg" },
  { word: "sandwich", image: "assets/images/sandwich.svg" },
  { word: "kangaroo", image: "assets/images/kangaroo.svg" },
  { word: "squirrel", image: "assets/images/squirrel.svg" },
  { word: "dinosaur", image: "assets/images/dinosaur.svg" },
  { word: "tortoise", image: "assets/images/tortoise.svg" },
  { word: "ladybird", image: "assets/images/ladybird.svg" },

  { word: "chocolate", image: "assets/images/chocolate.svg" },
  { word: "spaghetti", image: "assets/images/spaghetti.svg" },
  { word: "crocodile", image: "assets/images/crocodile.svg" },
  { word: "butterfly", image: "assets/images/butterfly.svg" },
  { word: "pineapple", image: "assets/images/pineapple.svg" },

  { word: "watermelon", image: "assets/images/watermelon.svg" },
  { word: "strawberry", image: "assets/images/strawberry.svg" },
  { word: "helicopter", image: "assets/images/helicopter.svg" },
];
