// Word list for Miles' Spelling Game.
// tier 1 = 3-4 letter, tier 2 = 5-6 letter,
// tier 3 = 7-8 letter, tier 4 = 9-10 letter words.
// Images: Twemoji (CC-BY 4.0) - see ATTRIBUTIONS.md
const WORDS = [
  { word: "cat", tier: 1, image: "assets/images/cat.svg" },
  { word: "dog", tier: 1, image: "assets/images/dog.svg" },
  { word: "sun", tier: 1, image: "assets/images/sun.svg" },
  { word: "hat", tier: 1, image: "assets/images/hat.svg" },
  { word: "pig", tier: 1, image: "assets/images/pig.svg" },
  { word: "cup", tier: 1, image: "assets/images/cup.svg" },
  { word: "bed", tier: 1, image: "assets/images/bed.svg" },
  { word: "fox", tier: 1, image: "assets/images/fox.svg" },
  { word: "bus", tier: 1, image: "assets/images/bus.svg" },
  { word: "egg", tier: 1, image: "assets/images/egg.svg" },
  { word: "box", tier: 1, image: "assets/images/box.svg" },
  { word: "hen", tier: 1, image: "assets/images/hen.svg" },
  { word: "bag", tier: 1, image: "assets/images/bag.svg" },
  { word: "van", tier: 1, image: "assets/images/van.svg" },
  { word: "key", tier: 1, image: "assets/images/key.svg" },
  { word: "owl", tier: 1, image: "assets/images/owl.svg" },
  { word: "cow", tier: 1, image: "assets/images/cow.svg" },
  { word: "bee", tier: 1, image: "assets/images/bee.svg" },

  { word: "frog", tier: 1, image: "assets/images/frog.svg" },
  { word: "lion", tier: 1, image: "assets/images/lion.svg" },
  { word: "duck", tier: 1, image: "assets/images/duck.svg" },
  { word: "fish", tier: 1, image: "assets/images/fish.svg" },
  { word: "bird", tier: 1, image: "assets/images/bird.svg" },
  { word: "boat", tier: 1, image: "assets/images/boat.svg" },
  { word: "bear", tier: 1, image: "assets/images/bear.svg" },
  { word: "sofa", tier: 1, image: "assets/images/sofa.svg" },

  { word: "train", tier: 2, image: "assets/images/train.svg" },
  { word: "monkey", tier: 2, image: "assets/images/monkey.svg" },
  { word: "chair", tier: 2, image: "assets/images/chair.svg" },
  { word: "guitar", tier: 2, image: "assets/images/guitar.svg" },
  { word: "cheese", tier: 2, image: "assets/images/cheese.svg" },
  { word: "chips", tier: 2, image: "assets/images/chips.svg" },
  { word: "potato", tier: 2, image: "assets/images/potato.svg" },
  { word: "orange", tier: 2, image: "assets/images/orange.svg" },
  { word: "pepper", tier: 2, image: "assets/images/pepper.svg" },
  { word: "lemon", tier: 2, image: "assets/images/lemon.svg" },
  { word: "cereal", tier: 2, image: "assets/images/cereal.svg" },
  { word: "sheep", tier: 2, image: "assets/images/sheep.svg" },
  { word: "horse", tier: 2, image: "assets/images/horse.svg" },
  { word: "zebra", tier: 2, image: "assets/images/zebra.svg" },
  { word: "koala", tier: 2, image: "assets/images/koala.svg" },
  { word: "camel", tier: 2, image: "assets/images/camel.svg" },
  { word: "snake", tier: 2, image: "assets/images/snake.svg" },
  { word: "whale", tier: 2, image: "assets/images/whale.svg" },
  { word: "shark", tier: 2, image: "assets/images/shark.svg" },
  { word: "mouse", tier: 2, image: "assets/images/mouse.svg" },
  { word: "rabbit", tier: 2, image: "assets/images/rabbit.svg" },
  { word: "turtle", tier: 2, image: "assets/images/turtle.svg" },
  { word: "parrot", tier: 2, image: "assets/images/parrot.svg" },
  { word: "spider", tier: 2, image: "assets/images/spider.svg" },

  { word: "giraffe", tier: 3, image: "assets/images/giraffe.svg" },
  { word: "elephant", tier: 3, image: "assets/images/elephant.svg" },
  { word: "sandwich", tier: 3, image: "assets/images/sandwich.svg" },
  { word: "dolphin", tier: 3, image: "assets/images/dolphin.svg" },
  { word: "gorilla", tier: 3, image: "assets/images/gorilla.svg" },
  { word: "penguin", tier: 3, image: "assets/images/penguin.svg" },
  { word: "octopus", tier: 3, image: "assets/images/octopus.svg" },
  { word: "kangaroo", tier: 3, image: "assets/images/kangaroo.svg" },
  { word: "squirrel", tier: 3, image: "assets/images/squirrel.svg" },

  { word: "chocolate", tier: 4, image: "assets/images/chocolate.svg" },
  { word: "spaghetti", tier: 4, image: "assets/images/spaghetti.svg" },
  { word: "crocodile", tier: 4, image: "assets/images/crocodile.svg" },
  { word: "watermelon", tier: 4, image: "assets/images/watermelon.svg" },
];
